### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by VpopUnik** [lmueller27/Fusion360PatternsAndTextures#3]
Installed this add in but can't get it to work.
I created a solid "plank" body and converted it to a mesh as a test. However, when I try add noise, grunge map or whatever I get this error.
![image](https://github.com/lmueller27/Fusion360PatternsAndTextures/assets/138257973/5c0d01ef-6173-4ecc-8c38-20cc2978fd40)

**Comment by lmueller27** [comment]
I'll look into this later, thank you.

**Comment by lmueller27** [comment]
The bug was caused by your test mesh having less than 20 vertices. This caused a 0 division in my lazy progress dialog. 
It is fixed now, but I encourage you to try the algorithms on meshes with more vertices. When creating mesh bodies from bodies (with the tesselate function) you can specify the resolution by lowering the maximum edge length setting.
